OPENQASM 3.0;
include "stdgates.inc";
bit[4] synd;
bit[2] logic;
qubit[9] data;
qubit[1] readout;
qubit[4] ancilla;
barrier data[0], data[1], data[2], data[3], data[4], data[5], data[6], data[7], data[8], ancilla[0], ancilla[1], ancilla[2], ancilla[3];
reset ancilla[0];
reset ancilla[1];
reset ancilla[2];
reset ancilla[3];
cx data[0], ancilla[0];
cx data[1], ancilla[0];
cx data[3], ancilla[0];
cx data[4], ancilla[0];
synd[0] = measure ancilla[0];
h ancilla[1];
cz ancilla[1], data[4];
cz ancilla[1], data[5];
cz ancilla[1], data[7];
cz ancilla[1], data[8];
h ancilla[1];
synd[1] = measure ancilla[1];
reset readout[0];
cx data[0], readout[0];
cx data[1], readout[0];
cx data[2], readout[0];
cx data[3], readout[0];
cx data[4], readout[0];
cx data[5], readout[0];
cx data[6], readout[0];
cx data[7], readout[0];
cx data[8], readout[0];
logic[0] = measure readout[0];
barrier data[0], data[1], data[2], data[3], data[4], data[5], data[6], data[7], data[8], ancilla[0], ancilla[1], ancilla[2], ancilla[3];
reset ancilla[0];
reset ancilla[1];
reset ancilla[2];
reset ancilla[3];
cx data[0], ancilla[0];
cx data[1], ancilla[0];
cx data[3], ancilla[0];
cx data[4], ancilla[0];
synd[0] = measure ancilla[0];
h ancilla[1];
cz ancilla[1], data[4];
cz ancilla[1], data[5];
cz ancilla[1], data[7];
cz ancilla[1], data[8];
h ancilla[1];
synd[1] = measure ancilla[1];
reset readout[0];
cx data[0], readout[0];
cx data[1], readout[0];
cx data[2], readout[0];
cx data[3], readout[0];
cx data[4], readout[0];
cx data[5], readout[0];
cx data[6], readout[0];
cx data[7], readout[0];
cx data[8], readout[0];
logic[1] = measure readout[0];
